version: '3.1'

services:
  livedivulgador:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    build:
      context: ./docker/
      dockerfile: postgres.dockerfile
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    restart: always
