version: '3.1'

services:
  livedivulgador:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env

  db:
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${user_db}
      POSTGRES_PASSWORD: ${passwd_db}
      POSTGRES_DB: streamers
    build:
      context: ./docker/
      dockerfile: postgres.dockerfile
